import express from 'express';
import { format, parseISO, addDays } from 'date-fns';
import CalendarEntry from '../models/CalendarEntry.js';
import LeaveBalance from '../models/LeaveBalance.js';
import Company from '../models/Company.js';
import Notification from '../models/Notification.js';
import { protect } from '../middleware/auth.js';
import { checkWfhWarning, suggestBestWfhDays } from '../utils/wfhLogic.js';

const router = express.Router();

// Get entries for a year or month
router.get('/', protect, async (req, res) => {
  try {
    const { year, month } = req.query;
    const filter = { userId: req.user._id };
    if (year) filter.year = parseInt(year);
    if (month) filter.month = parseInt(month);
    const entries = await CalendarEntry.find(filter).sort({ date: 1 });
    res.json(entries);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// Add or update a single entry
router.post('/', protect, async (req, res) => {
  try {
    const { date, type, leaveType, note } = req.body;
    if (!date || !type) return res.status(400).json({ message: 'date and type required' });

    const dateObj = parseISO(date);
    const year = dateObj.getFullYear();
    const month = dateObj.getMonth() + 1;

    // Get company for warnings
    const company = await Company.findById(req.user.companyId);
    const holidays = company?.publicHolidays || [];

    let warnings = [];

    if (type === 'WFH') {
      // Check monthly WFH quota
      const monthEntries = await CalendarEntry.find({ userId: req.user._id, year, month, type: 'WFH' });
      const allWfhDates = monthEntries.map(e => e.date);

      if (monthEntries.length >= (company?.wfhPerMonth || 8)) {
        return res.status(400).json({ message: `WFH quota for this month (${company?.wfhPerMonth || 8}) already reached` });
      }

      warnings = checkWfhWarning(date, company?.preferredWfhDays || [4, 5], allWfhDates);
    }

    // Upsert entry
    const entry = await CalendarEntry.findOneAndUpdate(
      { userId: req.user._id, date },
      { userId: req.user._id, date, type, leaveType, note, year, month },
      { upsert: true, new: true }
    );

    // Update leave balance
    if (type === 'LEAVE' && leaveType) {
      await LeaveBalance.findOneAndUpdate(
        { userId: req.user._id, year, 'balances.leaveKey': leaveType },
        { $inc: { 'balances.$.used': 1 } }
      );
    }

    // Create warning notifications
    for (const w of warnings) {
      await Notification.create({
        userId: req.user._id,
        title: w.type === 'PREFERENCE' ? 'WFH Preference Warning' : 'Long Weekend Warning',
        message: w.message,
        type: 'WARNING',
        relatedDate: date
      });
    }

    res.json({ entry, warnings });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// Delete / clear an entry
router.delete('/:date', protect, async (req, res) => {
  try {
    const { date } = req.params;
    const entry = await CalendarEntry.findOneAndDelete({ userId: req.user._id, date });
    if (!entry) return res.status(404).json({ message: 'Entry not found' });

    // Restore leave balance
    if (entry.type === 'LEAVE' && entry.leaveType) {
      const year = parseISO(date).getFullYear();
      await LeaveBalance.findOneAndUpdate(
        { userId: req.user._id, year, 'balances.leaveKey': entry.leaveType },
        { $inc: { 'balances.$.used': -1 } }
      );
    }

    res.json({ message: 'Deleted' });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// Bulk set WFH for a month (auto-generate)
router.post('/bulk-wfh', protect, async (req, res) => {
  try {
    const { year, month, dates } = req.body;
    const company = await Company.findById(req.user.companyId);

    // Clear existing auto-generated WFH for this month
    await CalendarEntry.deleteMany({ userId: req.user._id, year, month, type: 'WFH', autoGenerated: true });

    const ops = dates.map(date => ({
      updateOne: {
        filter: { userId: req.user._id, date },
        update: { userId: req.user._id, date, type: 'WFH', year, month, autoGenerated: true },
        upsert: true
      }
    }));
    await CalendarEntry.bulkWrite(ops);

    res.json({ message: `${dates.length} WFH days set for ${year}-${month}` });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// Get WFH suggestions for a month
router.get('/suggest-wfh', protect, async (req, res) => {
  try {
    const { year, month } = req.query;
    const y = parseInt(year), m = parseInt(month);
    const company = await Company.findById(req.user.companyId);

    // Get ALL entries for this month to know what's blocked
    const monthEntries = await CalendarEntry.find({ userId: req.user._id, year: y, month: m });
    const existingWfh = monthEntries.filter(e => e.type === 'WFH').map(e => e.date);
    const blockedDates = monthEntries
      .filter(e => e.type === 'LEAVE' || e.type === 'HOLIDAY')
      .map(e => e.date);

    const remaining = (company?.wfhPerMonth || 8) - existingWfh.length;

    const suggestions = suggestBestWfhDays(
      y, m,
      company?.preferredWfhDays || [4, 5],
      remaining,
      company?.publicHolidays || [],
      existingWfh,
      blockedDates  // ← new param
    );
    res.json({ suggestions });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

export default router;
