import mongoose from 'mongoose';

const calendarEntrySchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  date: { type: String, required: true }, // YYYY-MM-DD
  type: {
    type: String,
    enum: ['WFH', 'LEAVE', 'HOLIDAY', 'OFFICE'],
    required: true
  },
  leaveType: { type: String }, // PL, ML, EL etc - only if type=LEAVE
  note: { type: String },
  year: { type: Number, required: true },
  month: { type: Number, required: true },
  isHoliday: { type: Boolean, default: false },
  holidayName: { type: String },
  autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

calendarEntrySchema.index({ userId: 1, date: 1 }, { unique: true });
calendarEntrySchema.index({ userId: 1, year: 1, month: 1 });

export default mongoose.model('CalendarEntry', calendarEntrySchema);
